openapi: 3.1.0
x-stoplight:
  id: 13ugbg96utt3a
info:
  title: isupipe
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /tag:
    parameters: []
    get:
      summary: ''
      operationid: get-tag
      responses:
        '200':
          $ref: '#/components/responses/GetTag'
      description: サービスで提供されているタグの一覧取得
  /login:
    parameters: []
    post:
      summary: ''
      operationId: post-login
      responses:
        '200':
          description: OK
      description: ログイン
      requestBody:
        $ref: '#/components/requestBodies/Login'
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '201':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      description: ユーザ登録
      requestBody:
        $ref: '#/components/requestBodies/PostUser'
  '/users/{userid}':
    parameters:
      - schema:
          type: string
        name: userid
        in: path
        required: true
    get:
      summary: ''
      operationId: get-users-userid
      responses:
        '200':
          $ref: '#/components/responses/GetUser'
      description: ユーザプロフィール取得
      parameters:
        - schema:
            type: string
          in: cookie
          name: SESSIONID
          description: セッションID
  '/users/{userid}/statistics':
    parameters:
      - schema:
          type: string
        name: userid
        in: path
        required: true
    get:
      summary: ''
      operationId: get-users-statistics
      responses:
        '200':
          $ref: '#/components/responses/GetUserStatistics'
      description: ユーザの配信に関する統計情報取得
      parameters:
        - schema:
            type: string
          in: cookie
          name: SESSIONID
          description: セッションID
  /livestream:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/GetLivestreams'
      operationId: get-livestream
      description: ライブストリームの情報取得エンドポイント
      parameters:
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
  '/livestream/{livestreamid}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/GetLivestream'
      operationId: 'get-livestream-:livestreamid'
      description: ライブストリーム視聴画面の情報取得
    parameters:
      - schema:
          type: string
        name: livestreamid
        in: path
        required: true
  '/livestream/{livestreamid}/superchat':
    get:
      summary: Your GET endpoint
      tags: []
      operationId: 'get-livestream-:livestreamid-superchat'
      description: 当該ライブストリームのスパチャ取得
      responses:
        '200':
          description: OK
        '201':
          description: Created
      requestBody:
        $ref: '#/components/requestBodies/PostSuperchat'
    parameters:
      - schema:
          type: string
        name: livestreamid
        in: path
        required: true
    post:
      summary: ''
      operationId: post-livestream-livestreamid-reaction
      requestBody:
        $ref: '#/components/requestBodies/PostReaction'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reaction'
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
      description: リアクション投稿
    post:
      summary: ''
      operationId: post-livestream-livestreamid-superchat
      requestBody:
        $ref: '#/components/requestBodies/PostSuperchat'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Superchat'
              examples:
                basic:
                  value:
                    id: 12
                    user_id: 5
                    livestream_id: 1
                    comment: がんばれ〜
                    tip: 500
                    created_at: 1695586243
                    updated_at: 1695586243
      parameters:
        - schema:
            type: string
          in: header
          name: Content-Type
          description: application/json
      description: スパチャ投稿
  '/livestream/{livestreamid}/statistics':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/GetLivestreamStatistics'
        '404': null
      operationId: 'get-livestream-:livestreamid-statistics'
      description: ライブストリームの統計情報取得
    parameters:
      - schema:
          type: string
        name: livestreamid
        in: path
        required: true
  /livestream/reservation:
    post:
      summary: ''
      operationId: post-livestream-reservation
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Livestream'
              examples:
                Example 1:
                  value:
                    id: 1
                    user_id: 12
                    title: ISUCON公式から出たゲームやるぞ！
                    description: 'お約束: マナーを守りましょう'
                    privacy_status: public
                    start_at: 12345
                    end_at: 12345
                    created_at: 12345
                    updated_at: 12345
      requestBody:
        $ref: '#/components/requestBodies/ReserveLivestream'
  '/search_livestream':
    parameters:
      - in: query
        name: tag
        schema:
          type: string
        description: 検索に使用するタグの名前
    get:
      summary: ''
      operationId: get-search-livestream
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Livestream'
  '/superchat/{superchatid}/report':
    parameters:
      - schema:
          type: string
        name: superchatid
        in: path
        required: true
    post:
      summary: ''
      operationId: post-superchat-superchatid-report
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuperchatReport'
              examples:
                Example 1:
                  value:
                    id: 1
                    user_id: 12
                    superchat_id: 153
                    created_at: 12345
                    updated_at: 12345
components:
  schemas:
    Theme:
      dark_mode:
        type: boolean
    Tag:
      id:
        type: integer
      name:
        type: string
      created_at:
        type: number
    Reaction:
      id:
        type: integer
      emoji_name:
        type: string
      user_id:
        type: integer
      livestream_id:
        type: integer
      created_at:
        type: integer
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 0
          name: alice
          display_name: alice_display
          description: alice@example.com
          created_at: true
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        name:
          type: string
        display_name:
          type: string
        description:
          type: string
          format: email
        created_at:
          type: integer
      required:
        - id
        - name
        - display_name
        - description
    Livestream:
      title: Livestream
      x-stoplight:
        id: 7t0r49gwe046a
      type: object
      properties:
        id:
          type: number
        user_id:
          type: number
        title:
          type: string
        description:
          type: string
        privacy_status:
          type: string
        start_at:
          type: number
        end_at:
          type: number
        created_at:
          type: number
        updated_at:
          type: number
    LivestreamView:
      title: LivestreamView
      x-stoplight:
        id: qs78k91gl10ju
      type: object
      properties:
        id:
          type: number
        owner_id:
          type: number
        channel_id:
          type: number
        title:
          type: string
        description:
          type: string
        playlist_url:
          type: string
        start_at:
          type: number
        end_at:
          type: number
        created_at:
          type: number
        updated_at:
          type: number
    Superchat:
      title: Superchat
      x-stoplight:
        id: xefjzrvtkos6j
      type: object
      description: 上位チャットの投稿
      properties:
        id:
          type: number
        user_id:
          type: number
        livestream_id:
          type: number
        comment:
          type: string
        tip:
          type: number
        created_at:
          type: number
        updated_at:
          type: number
    LivesteamStatistics:
      title: LivesteamStatistics
      type: object
      properties:
        total_viewers:
          type: number
        total_tips:
          type: number
        total_superchats:
          type: number
        total_reactions:
          type: number
        previous_livestream_total_viewers_diff:
          type: number
        previous_livestream_total_tips_diff:
          type: number
        previous_livestream_total_superchats_diff:
          type: number
        previous_livestream_total_reactions_diff:
          type: number
    UserStatistics:
      title: LivesteamStatistics
      type: object
      properties:
        average_viewers:
          type: number
        average_tips:
          type: number
        average_superchats:
          type: number
        average_reactions:
          type: number
    SuperchatReport:
      title: SuperchatReport
      x-stoplight:
        id: ubl7oq4t4kkn8
      type: object
      properties:
        id:
          type: number
        user_id:
          type: number
        superchat_id:
          type: number
        created_at:
          type: number
        updated_at:
          type: number
  requestBodies:
    PostUser:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              display_name:
                type: string
              description:
                type: string
              password:
                type: string
              theme:
                $ref: "#/components/schemas/Theme"
          examples:
            example-1:
              value:
                name: johndoe
                display_name: johndoe_display
                description: blah blah blah
                password: s3cr3t
                theme:
                  dark_mode: true
                created_at: 1234567
    Login:
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
    PostReaction:
      content:
        application/json:
          schema:
            type: object
            properties:
              emoji_name:
                type: string
          examples:
            Example 1:
              value:
                emoji_name: ":innocent:"
    PostSuperchat:
      content:
        application/json:
          schema:
            type: object
            properties:
              comment:
                type: string
              tip:
                type: number
          examples:
            Example 1:
              value:
                comment: がんばれ〜
                tip: 500
    ReserveLivestream:
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
              privacy_status:
                type: string
              start_at:
                type: number
              end_at:
                type: number
          examples:
            Example 1:
              value:
                title: ISUCON公式から出たゲームやるぞ！
                description: '配信のマナー: ★みんな仲良くしましょう★'
                privacy_status: public
                start_at: 0
                end_at: 0
  responses:
    GetTag:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Tag'
    GetUser:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
    GetUserStatistics:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserStatistics'
    GetLivestreams:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Livestream'
    GetLivestream:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LivestreamView'
    GetLivestreamStatistics:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LivesteamStatistics'
    GetSuperchats:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Superchat'
  examples: {}
